use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :livevox, LivevoxWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/parcel-bundler/bin/cli.js",
      "watch",
      "lib/livevox_web/static/js/app.js",
      "--out-dir",
      "priv/static/js"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n", level: :info
config :rollbax, enabled: false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :livevox,
  access_token: System.get_env("LIVEVOX_ACCESS_TOKEN"),
  clientname: System.get_env("LIVEVOX_CLIENT_NAME"),
  username: System.get_env("LIVEVOX_USERNAME"),
  password: System.get_env("LIVEVOX_PASSWORD"),
  data_dog_api_key: System.get_env("DATA_DOG_API_KEY"),
  data_dog_application_key: System.get_env("DATA_DOG_APP_KEY"),
  airtable_key: System.get_env("AIRTABLE_KEY"),
  airtable_base: System.get_env("AIRTABLE_BASE"),
  airtable_table_name: System.get_env("AIRTABLE_TABLE_NAME"),
  mongodb_username: System.get_env("MONGO_USERNAME"),
  mongodb_seeds: [
    System.get_env("MONGO_SEED_1"),
    System.get_env("MONGO_SEED_2")
  ],
  mongodb_password: System.get_env("MONGO_PASSWORD"),
  mongodb_port: System.get_env("MONGO_PORT"),
  login_management_url: System.get_env("LOGIN_MANAGEMENT_URL"),
  message_engine_key: System.get_env("MESSAGE_ENGINE_KEY"),
  message_engine_base: System.get_env("MESSAGE_ENGINE_BASE"),
  message_engine_table_name: System.get_env("MESSAGE_ENGINE_TABLE_NAME"),
  on_new_dashboard_webhook: System.get_env("ON_NEW_DASHBOARD_WEBHOOK"),
  test: true

config :rollbax,
  access_token: System.get_env("ROLLBAR_ACCESS_TOKEN"),
  environment: "development"
